# EMBEDDED SERVER CONFIGURATION
server.port=${port}
server.servlet.session.timeout=30m

jwt.secret=javainuse

# DATASOURCE
spring.datasource.continue-on-error=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ec2-54-246-84-100.eu-west-1.compute.amazonaws.com:5432/d344qvedh8tei4
# JDBC URL of the database.
spring.datasource.name=d344qvedh8tei4
spring.datasource.username=hfynuunncocbpl
# Login username of the database.
spring.datasource.password=a39b11109acb19d4c76cd3881dc6e0e6a388334e374180899c8bb86e4e1d7599
spring.datasource.platform=d344qvedh8tei4

spring.datasource.hikari.connection-timeout=20000
#maximum number of milliseconds that a client will wait for a connection
spring.datasource.hikari.minimum-idle=2
#minimum number of idle connections maintained by HikariCP in a connection pool
spring.datasource.hikari.maximum-pool-size=8
#maximum pool size
spring.datasource.hikari.idle-timeout=10000
#maximum idle time for connection
spring.datasource.hikari.max-lifetime=1000
# maximum lifetime in milliseconds of a connection in the pool after it is closed.
spring.datasource.hikari.auto-commit=true
#default auto-commit behavior.
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

# JPA
spring.jpa.generate-ddl=true
# Whether to initialize the schema on startup.
#spring.jpa.hibernate.ddl-auto=create
# DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Defaults to "create-drop" when using an embedded database and no schema manager was detected. Otherwise, defaults to "none".
spring.jpa.show-sql=true
#spring.jpa.database=spring_test
# Target database to operate on, auto-detected by default. Can be alternatively set using the "databasePlatform" property.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false