FROM adoptopenjdk/openjdk11

RUN apt-get update --fix-missing

#RUN apt-get upgrade -y

RUN apt-get install -y apt-utils \
	&& apt-get install -y curl \
	&& apt-get install -y net-tools \
	&& apt-get install -y software-properties-common \
	&& apt-get install -y gnupg gnupg1 gnupg2

RUN apt-get install -y wget \
	&& apt-get install -y apt-transport-https \
	&& apt-get install -y ca-certificates \
	&& apt-get install -y dirmngr \
	&& apt-get install -y maven

RUN apt-get install -y postgresql-client

WORKDIR /home/EagleEyeWing
